# Generated by Django 3.1.4 on 2020-12-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdlist', '0002_auto_20201214_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdlistings',
            name='main_track',
        ),
    ]
