# Generated by Django 3.1.4 on 2020-12-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdlist', '0003_remove_birdlistings_main_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdlistings',
            name='info',
        ),
        migrations.RemoveField(
            model_name='birdlistings',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='birdlistings',
            name='uploaded_by',
        ),
    ]
