# Generated by Django 3.1.4 on 2020-12-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdlist', '0004_auto_20201215_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdlistings',
            name='bird_name',
            field=models.CharField(blank=True, default='name plz', max_length=100),
        ),
    ]
