# Generated by Django 3.1.4 on 2020-12-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Track_name', models.CharField(max_length=100)),
                ('track_1', models.FileField(upload_to='audio/%Y/%m/%d/')),
                ('track_2', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('track_3', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('track_4', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('track_5', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('track_6', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('track_7', models.FileField(blank=True, upload_to='audio/%Y/%m/%d/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
