# Generated by Django 3.1.4 on 2020-12-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20201214_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_1',
            field=models.FileField(upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_2',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_3',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_4',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_5',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_6',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_7',
            field=models.FileField(blank=True, upload_to='track/%Y/%m/%d/'),
        ),
    ]
