# Generated by Django 3.1.4 on 2020-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_remove_track_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='Track_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
