# Generated by Django 3.1.4 on 2020-12-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_track_track_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='uploaded_by',
        ),
    ]
