# Generated by Django 3.1.4 on 2020-12-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_image_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
