# Generated by Django 3.1.4 on 2020-12-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdlist', '0006_auto_20201215_2305'),
        ('image', '0004_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='image',
            name='bird',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='birdlist.birdlistings'),
        ),
    ]
