# Generated by Django 3.1.4 on 2020-12-14 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birdinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_Name', models.CharField(max_length=100)),
                ('sci_Name', models.CharField(max_length=100)),
                ('Klass', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('wiki_link', models.CharField(max_length=200)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
