# Generated by Django 3.1.4 on 2020-12-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdinfo', '0003_birdinfo_bird'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdinfo',
            name='uploaded_by',
        ),
    ]
